version: "3.8"

services:
  scrollr-rss-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: scrollr-rss-api
    ports:
      - "8083:8083"
    environment:
      - DATABASE_URL={{ environment.DATABASE_URL }}
      - REDIS_URL={{ environment.REDIS_URL }}
      - ENCRYPTION_KEY={{ environment.ENCRYPTION_KEY }}
      - ALLOWED_ORIGINS={{ environment.ALLOWED_ORIGINS }}
      - INTEGRATION_URL={{ environment.INTEGRATION_URL }}
      - INTERNAL_RSS_URL=http://scrollr-rss-service:3004
    restart: unless-stopped

  scrollr-rss-service:
    build:
      context: ./service
      dockerfile: Dockerfile
    container_name: scrollr-rss-service
    ports:
      - "3004:3004"
    environment:
      - DATABASE_URL={{ environment.DATABASE_URL }}
    restart: unless-stopped
