version: "3.8"

services:
  scrollr-finance-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: scrollr-finance-api
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL={{ environment.DATABASE_URL }}
      - REDIS_URL={{ environment.REDIS_URL }}
      - ENCRYPTION_KEY={{ environment.ENCRYPTION_KEY }}
      - ALLOWED_ORIGINS={{ environment.ALLOWED_ORIGINS }}
      - INTEGRATION_URL={{ environment.INTEGRATION_URL }}
      - INTERNAL_FINANCE_URL=http://scrollr-finance-service:3001
    restart: unless-stopped

  scrollr-finance-service:
    build:
      context: ./service
      dockerfile: Dockerfile
    container_name: scrollr-finance-service
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL={{ environment.DATABASE_URL }}
      - FINNHUB_API_KEY={{ environment.FINNHUB_API_KEY }}
    restart: unless-stopped
